[profile.default]
src = 'contracts'
out = 'out'
test = "test"
libs = ['lib', "node_modules"]
gas_reports = ["*"]
optimizer = true
optimizer_runs = 20000

[rpc_endpoints]
goerli = "${GOERLI_RPC_URL}"

[etherscan]
goerli = { key = "${ETHERSCAN_API_KEY}" }

[fmt]
tab_width = 2


# See more config options https://github.com/foundry-rs/foundry/tree/master/config
